---

# Tasks file for aptly

- name : Import aptly GPG key
  become : True
  apt_key :
    id : "{{ aptly_gpg_key }}"
    keyserver : "{{ aptly_gpg_keyserver }}"
    state : present

- name : Install aptly repository
  become : True
  apt_repository :
    repo : "{{ aptly_repository }}"
    update_cache : True
    state : present

- name : Create aptly user
  become : True
  user :
    name : "{{ aptly_user }}"
    comment : "User for aptly repository management"
    home : "{{ aptly_user_home }}"
    shell : "/bin/false"

- name : Change home permission
  become : True
  file :
    dest : "{{ aptly_user_home }}"
    mode : "0700"

- name : Install aptly package
  become : True
  apt :
    name : "aptly"
    cache_valid_time : 3600
    update_cache : True
    state : present

- name : Generate configuration
  become : True
  become_user : "{{ aptly_user }}"
  template :
    src : "{{ role_path }}/templates/aptly.conf.j2"
    dest : "{{ aptly_user_home }}/.aptly.conf"
    mode : "0700"
